config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/oauth/callback', to: 'instagram#callback'
  get 'users/show'
  get '/design', to: 'static_pages#design', as: 'design'
  get '/care', to: 'static_pages#care', as: 'care'
  get '/care/:doctor', to: 'static_pages#care', as: 'care_doctor'
  get '/cart', to: 'static_pages#cart', as: 'cart'
  get '/admin', to: 'static_pages#admin', as: 'admin'
  get '/sellables/new', to: 'products#sellables', as: 'new_sellable'
  devise_for :user

  resources :users, only: [:show]
  resources :products
  resources :plants
  resources :accessories
  resources :carts do 
    resources :cart_products
  end

  get '/admin/products', to: 'products#admin_products', as: 'admin_products'

  get 'hello_world', to: 'hello_world#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :sellable, polymorphic: true
  has_many :cart_products
  has_many :reviews
  has_and_belongs_to_many :users
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "admin", only: [:new, :admin_products, :update, :edit, :create, :destroy]

  def index
    @plants = Plant.all
    @products = Product.all
    @product = Product.find_by(params[:id])
  end

  def show
    @plants = Plant.all
  end

  # Admin actions

  def new
    @product = Product.new
  end

  def create
    redirect_to send(new_path(type: params['product']['sellable_type'], product_params: product_params ) )
  end

  def sellables
    @plant = Plant.new
    @accessory = Accessory.new
    @product = Product.find(params[:product_id])
  end

  def admin_products
    @products = Product.all
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_back(fallback_location: admin_path)
  end

  private

  def product_params
    params.require(:product).permit(:sku, :price, :sellable_type)
  end
end

app/views/products/_form.html.erb
<div class="form-group">
  <%= form.label :sku %>
  <%= form.text_field :sku, class:"form-control", required: true %>
</div>
<div class="form-group">
  <%= form.label :price %> <br/>
  <%= form.number_field :price, class:"form-control", required: true %>
</div>
<div class="form-group">
  <%= form.label 'Inventory amount' %> <br/>
  <%= form.number_field :amount, class:"form-control", required: true %>
</div>

app/views/products/admin_products.html.erb
 <div class="row">
 <div class="col-8 offset-2">
  <form method="GET">
    <label>Add a product to the Inventory</label>
    <div class="row">
      <div class="col-6">
        <%= submit_tag 'Add a Plant', formaction: new_plant_path, class: 'btn btn-block btn-outline-success' %>
      </div>
      <div class="col-6">
        <%= submit_tag 'Add an Accessory', formaction: new_accessory_path, class: 'btn btn-block btn-outline-info' %>
      </div>
    </div>
  </select>
</div>

<div class="row">
  <% @products.each_with_index do |product, i| %>
    <div class="col col-sm-6 col-md-3 mt-3">
      <div class="card">
        <% if product.sellable.images.empty? %>
          <%= image_tag 'http://placepuppy.net/100/100' %>
        <% else %>
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
            <% product.sellable.images.each do |img| %>
              <div class="carousel-item active">
                <%= image_tag img, height: 100 %>
              </div>
            <% end %>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.sellable.name %></h5>
          <p class="card-text"><%=product.sellable.description %></p>
          <dl>
            <dt>test</dt>
            <dd>data</dd>
          </dl>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-sm btn-primary' %></td>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div id="products-wrapper">
  <h1 class="product-filter-header">Choose your Plant</h1>
  <%= react_component 'Plants', props: { filters: @filters }, prerender: false %>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product %>



<%#= form_with(model: @product, local: true) do |form| %>
  <%# <div class="form-group col-md-3"> %>
    <%#= form.label :sku %>
    <%#= form.text_field :sku, class:"form-control" %>
  <%# </div> %>
  <%# <div class="form-group col-md-3"> %>
    <%#= form.label :price %>
    <%#= form.text_field :price, class:"form-control" %>
  <%# </div> %>
  <%# <div class="form-group col-md-3"> %>
    <%#= form.select :sellable_type, ['Plant', 'Accessory']%>
    <%#= form.check_box(:sellable_type) %>
    <%#= form.label(:sellable_type, "Plant") %>
    <%#= form.check_box(:sellable_type) %>
    <%#= form.label(:sellable_type, "Accessory") %>
  <%# </div> %>
  <%#= form.hidden_field :sellable_id, value: @product, class:"form-control" %>
  <%# <button type="submit" class="btn btn-primary">Submit</button> %>
<%# end %>

app/views/products/sellables.html.erb
<h1>Create new product</h1>

<%= render 'new' %>