config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/oauth/callback', to: 'instagram#callback'
  get 'users/show'
  get '/design', to: 'static_pages#design', as: 'design'
  get '/care', to: 'static_pages#care', as: 'care'
  get '/care/:doctor', to: 'static_pages#care', as: 'care_doctor'
  get '/cart', to: 'static_pages#cart', as: 'cart'
  get '/admin', to: 'static_pages#admin', as: 'admin'
  get '/sellables/new', to: 'products#sellables', as: 'new_sellable'
  devise_for :user

  resources :users, only: [:show]
  resources :products
  resources :plants
  resources :accessories
  resources :carts do 
    resources :cart_products
  end

  get '/admin/products', to: 'products#admin_products', as: 'admin_products'

  get 'hello_world', to: 'hello_world#index'
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  has_many_attached :images
  has_many :products, as: :sellable, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :image
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def to_json(options={})
    {
      id: self.id,
      sku: self.product.sku,
      price: self.product.price,
      amount: self.amount,
      sellableType: self.product.sellable_type,
      sellableId: self.product.sellable_id,
    }
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_one :products, as: :sellable, dependent: :destroy
  has_many_attached :images

  enum size: ['small', 'meduim', 'large']
  enum light: ['low', 'partial', 'full']
  enum maintenance: ['easy', 'intermediate', 'hard']
  enum category: ['herb', 'houseplant']

  scope :by_size, -> (size) { where('size IN (?)', size) }
  scope :by_light, -> (light) { where('light IN (?)', light) }
  scope :by_maintenance, -> (maintenance) { where('maintenance IN (?)', maintenance) }
  scope :by_category, -> (category) { where('category IN (?)', category) }

  include Rails.application.routes.url_helpers
  def to_json(options={})
    images = self.images.count > 0 ? self.images.map{ |img| rails_blob_path( img, only_path: true ) } : ['http://tinygarden-bucket.herokuapp.com/images/aloe.png']
    {
      name: name,
      description: description,
      images: images,
      size: size,
      maintenance: maintenance,
      light: light,
      category: category,
      url: url,
    }
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :sellable, polymorphic: true
  has_many :cart_products
  has_many :reviews
  has_and_belongs_to_many :users
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_one_attached :image
  has_one :cart
  has_and_belongs_to_many :products
  has_many :cart_products, through: :cart, source: 'products'
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, only: [:show, :edit, :destroy, :update] #you would put this in the UsersController
  def login_instagram
    Instagram.configure do |config|
      config.client_id = ENV['CLIENT_ID']
      config.client_secret = ENV['CLIENT_SECRET']
    end
    p ["loggging in",session[:access_token] ]
    if session[:access_token].nil?
      redirect_to Instagram.authorize_url(:redirect_uri => ENV['CALLBACK_URL'])
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :update]

  def index
  end 

  def show 
  end 
  

  def update 
    @cart.update(cart_params)
  end 

  private 
  def set_cart 
    @cart = current_user&.cart
  end 
  def cart_params 
    params.require(:cart).permit(:cart_products)
  end 
end 

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => ENV['CALLBACK_URL'])
    session[:access_token] = response.access_token
    redirect_to root_path
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit]
  layout "admin", only: :new
  def index
    @filters = [ # TODO: need to get filter values from Model. Like: Plant.categories
      [
        { value: 0, label: 'small' },
        { value: 1, label: 'medium' },
        { value: 2, label: 'large' }
      ],
      [
        { value: 0, label: 'low' },
        { value: 1, label: 'partial' },
        { value: 2, label: 'full' }
      ],
      [
        { value: 0, label: 'easy to care' },
        { value: 1, label: 'takes skill' },
        { value: 2, label: 'difficult to care' },
      ],
      [
        { value: 0, label: 'herb' },
        { value: 1, label: 'houseplant' },
      ]
    ]
    @plants = Plant.all
    @plants = @plants.by_size(params[:size]&.split(",")) if params[:size]&.split(",")&.any?
    @plants = @plants.by_light(params[:light]&.split(",")) if params[:light]&.split(",")&.any?
    @plants = @plants.by_maintenance(params[:maintenance]&.split(",")) if params[:maintenance]&.split(",")&.any?
    @plants = @plants.by_category(params[:category]&.split(",")) if params[:category]&.split(",")&.any?
    respond_to do |format|
      format.html {}
      format.json { render json: { plants: @plants } }
    end
  end

  def show
    respond_to do |format|
      format.html {}
      format.json { render json: @plant.to_json }
    end
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    if @plant.save
      Product.create(product_params.merge({sellable_type: 'Plant', sellable_id: @plant.id}))
      redirect_to admin_products_path
    else
      render 'new'
    end
  end

  def edit
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    ['size', 'light', 'maintenance', 'category'].each do |attr|
      params[:plant][attr] = params[:plant][attr].to_i
    end
    params.require(:plant).permit(:name, :size, :light, :maintenance, :category, :description, :images => [])
  end

  def product_params
    params.require(:plant).permit(:amount, :sku, :price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "admin", only: [:new, :admin_products, :update, :edit, :create, :destroy]

  def index
    @plants = Plant.all
    @products = Product.all
    @product = Product.find_by(params[:id])
  end

  def show
    @plants = Plant.all
  end

  # Admin actions

  def new
    @product = Product.new
  end

  def create
    redirect_to send(new_path(type: params['product']['sellable_type'], product_params: product_params ) )
  end

  def sellables
    @plant = Plant.new
    @accessory = Accessory.new
    @product = Product.find(params[:product_id])
  end

  def admin_products
    @products = Product.all
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_back(fallback_location: admin_path)
  end

  private

  def product_params
    params.require(:product).permit(:sku, :price, :sellable_type)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # before_action :login_instagram, only: [:landing]
  before_action :authenticate_user!, only: :admin
  layout "admin", only: :admin

  def landing
    @plants = Plant.limit(8)
    # @insta_feed = Instagram.client(:access_token => session[:access_token]).user_recent_media.shuffle.sample(4)
  end

  def care
    @doctor = params[:doctor] == 'doctor'
  end

  def doctor
  end

  def design
    if current_user
      @success_url = ENV['CREATE_SUCCESS_URL']
    else
      redirect_to root_path
    end
  end

  def cart
    if current_user
      @cart_items = current_user.cart.cart_products.map(&:to_json)
    else
      redirect_to root_path
    end
  end

  def admin
    if current_user.admin 
      @product = Product.new
    else 
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_user, only: :show
  
  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("Cart", props: @hello_world_props, prerender: false) %>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Tiny Garden | Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Navbar</span>
      <%= link_to "Products", admin_products_path, class: 'nav-link' %>
      <%#= link_to "Blogs", admin_blogs_path, class: 'nav-link' %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Tiny Garden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Grenze&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('http://tinygarden-bucket.herokuapp.com/images/Favicon/plant.png') %>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'product' %>
  </head>
  <body>
    <nav id="navbar" >
      <div id="inner-nav">
        <ul class="left-side-nav">
          <li><%= link_to "Shop", products_path, class: params[:action] == 'index' ? 'nav-active' : ''  %></li>
          <li id="care-nav-link"><%= link_to "Care", care_path, class: params[:action] == 'care' ? 'nav-active' : ''  %></li>
          <button class="btn-round yellow nav-design-btn" >
            <%= link_to "Design", design_path %>
          </button>
        </ul>
        <div class="animated bounce title">
          <%= link_to 'tiny garden', root_path %>
        </div>
        <div class="right-side-nav">
          <div class="dropdown" id="loginBox-position">
            <a href="#" id="drop-styles"><%= current_user ? "Account" : "login" %></a>
            <div class="dropdown-content">
              <%= link_to('Profile', current_user,
                class: ('nav-active' if params[:action] == 'show' && params[:controller] == 'users')) if current_user
              %>
              <%= link_to('Logout', destroy_user_session_path,
                method: 'delete',
                class: ('nav-active' if params[:action] == 'destroy' && params[:controller] == 'devise/registrations')) if current_user
              %>
              <%= link_to('Edit', edit_user_registration_path,
                class: ('nav-active' if params[:action] == 'edit' && params[:controller] == 'devise/registrations')) if current_user
              %>
              <%= link_to('Log In', new_user_session_path,
                class: ('nav-active' if params[:action] == 'new' && params[:controller] == 'devise/sessions')) unless current_user
              %>
              <%= link_to('Sign Up', new_user_registration_path,
                class: ('nav-active' if params[:action] == 'new' && params[:controller] == 'devise/registrations')) unless current_user
              %>
            </div>
          </div>
          <span id="cart" >
          <%= link_to image_tag("cart.png"), cart_path, 
            class: params[:action] == 'cart' ? 'nav-active' : ''
          %></span>
        </div>
      </div>
    </nav>
    <div id="main">
      <%= yield %>
    </div>
    <footer id="general-footer">
      <div class="footer-box">
        <div class="footer-left">
          <h2>tiny garden</h2>
          <p>Copyright. All rights reserved.</p>
          <p>All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means, including photocopying, recording, or other electronic or mechanical methods, without the prior written permission of the publisher, except in the case of brief quotations embodied in critical reviews and certain other noncommercial uses permitted by copyright law</p>
        </div>
        <div class="footer-right">
          <a id="facebook" href="https://www.facebook.com/" target="_blank">
            <%= image_tag 'http://tinygarden-bucket.herokuapp.com/images/facebookicon.png', alt: 'Facebook'%>
          </a>
          <a id="youtube" href="https://www.youtube.com/" target="_blank">
            <%= image_tag 'http://tinygarden-bucket.herokuapp.com/images/youtubeicon.png', alt: 'Youtube'%>
          </a>
          <a id="instagram" href="https://www.instagram.com/" target="_blank">
            <%= image_tag 'http://tinygarden-bucket.herokuapp.com/images/instaicon.png', alt: 'Instagram'%>
          </a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/utils/_image_previewer.html.erb
<div id="attachments"></div>

<script>
  // this awesome piece of code listens for change ion the input then creates a blob (temporary memory file) of the image and displays it in the empty div 🦄🌈😃
  const previewMultipleImages = e => {
    if (e.target.files && e.target.files[0]) {
      let mediaPreview = document.getElementById("attachments")
      mediaPreview.innerHTML = ""
      Array(e.target.files.length).fill().forEach( function(x, index) {
        let reader = new FileReader();
        reader.onload = ev => {
          let img = document.createElement("img")
          img.height = "200"
          img.src = ev.target.result
          mediaPreview.appendChild(img)
        }
        reader.readAsDataURL(e.target.files[index]);
      })
    }
  }
  document.getElementById('images-upload').addEventListener('change', previewMultipleImages)
</script>